# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d552f594c4997c48f7ce579df1ccbb17787a933394855e54b9f6e72ed7fc71d646dde2c724701accf0a26f21ffc887c92c4d9b1a8370c268786f8009e1e00352

test:
  secret_key_base: ccc0766d97e5a29fb749844555e3ebee666698730fcba161a50522e8c7a01844c5d1832de7cfc44c7eb2da544209dfadce0d4c8f426fabdff65b7f5f38663879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
